// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
const version = "0.1.0";
const cacheName = `anita-${version}`;

self.addEventListener('install', function(e) {
 e.waitUntil(
   caches.open(cacheName).then(function(cache) {
     return cache.addAll([
       '/',
       '/index.html',
       '/css/resume.min.css',
       '/vendor/bootstrap/css/bootstrap.min.css',
       '/vendor/fontawesome-free/css/all.min.css',
       'vendor/jquery/jquery.min.js',
       '/vendor/bootstrap/js/bootstrap.bundle.min.js',
       '/vendor/jquery-easing/jquery.easing.min.js',
       '/js/resume.min.js',
       '/img/profile.jpg'
     ]).then(() => self.skipWaiting());
   })
 );
});
self.addEventListener('activate', event => {
    event.waitUntil(self.clients.claim());
  });
  
  self.addEventListener('fetch', event => {
    event.respondWith(
      caches.open(cacheName)
        .then(cache => cache.match(event.request, {ignoreSearch: true}))
        .then(response => {
        return response || fetch(event.request);
      })
    );
  });